# 팀 공용 뷰 전용 프로필
# 로그인 화면처럼 DB 없이 확인 가능한 화면 작업에 사용
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration

spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
