# 팀 공유용 예시 설정 파일
# 이 파일을 참고해서 로컬의 application.properties 를 만든다.

spring.application.name=myddareungi
server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# docker notone0818/my-oracle-bike 기준 예시
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=secret이라 각자 입력
spring.datasource.password=secret이라 각자 입력

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB

mybatis.type-aliases-package=com.metanet.myddareungi
mybatis.mapper-locations=classpath*:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

secret.key= secret이라 각자 입력
